In [ ]:
import datetime
from dateutil import parser
import pandas as pd
import numpy as np
from datetime import date, timedelta


In [ ]:
# MERGED data
# From https://www.tutorialspoint.com/How-to-merge-multiple-files-into-a-new-file-using-Python
file_names = ["combined_data_1.txt", "combined_data_2.txt", "combined_data_3.txt", "combined_data_4.txt"]

with open("data.txt", "a") as outfile:
    for fname in file_names:
        with open(fname, "r") as infile:
            for line in infile:
                outfile.write(line)


In [ ]:
# finding the start and end of temporal data
small = datetime.datetime(2002, 1, 1)
big =  datetime.datetime(2002, 1, 1)


with open("data.txt") as infile:
    for line in infile:
        data = line.strip().split(',')
        if len(data) > 2:
            # From https://www.geeksforgeeks.org/nlp-using-dateutil-to-parse-dates/
            DT = parser.parse(data[2])
            if DT < small:
                small =DT
            if DT> big:
                big = DT
print(big)
print(small)

# 2005-12-31 00:00:00
# 1999-11-11 00:00:00

2005-12-31 00:00:00
1999-11-11 00:00:00


In [8]:
# get number of times user has rated an item
user={}
with open("data.txt") as infile:
    for line in infile:
        data = line.strip().split(',')
        if len(data) > 2:
            if data[0] not in user:
                user[data[0]]=1
            else:
                user[data[0]]+=1
            

In [9]:
print(len(user.keys()))
print(len(user))

480189
480189


In [10]:
userAll =open("userAll.txt","w")
for k in user.keys():
    userAll.write(k +",\n")

In [ ]:
# filter for any user with more than 100 ratings
# From https://stackoverflow.com/questions/8425046/the-best-way-to-filter-a-dictionary-in-python
filter = {k: v for k, v in user.items() if v >= 100}
# number of users who have more than 100 ratings

print(len(filter))


236117


In [19]:
# creating a user x time matrix
user_time={}
for users in filter:
    user_time[users]=[]

with open("data.txt") as infile:
    for line in infile:
        data = line.strip().split(',')
        if len(data) > 2:
            user =data[0]
            if user in filter:
                user_time[user].append(data[2])
            


In [20]:
print(user_time["1704416"])

['2004-06-01', '2004-05-24', '2004-11-17', '2004-10-05', '2004-09-09', '2005-02-06', '2004-05-24', '2004-08-14', '2005-04-19', '2004-05-25', '2004-09-08', '2004-07-28', '2004-08-10', '2004-06-24', '2005-02-06', '2004-11-01', '2004-10-02', '2004-10-24', '2004-08-16', '2005-04-08', '2004-05-24', '2004-06-02', '2004-06-02', '2004-08-04', '2005-08-16', '2005-11-07', '2004-07-28', '2004-06-12', '2004-08-16', '2005-07-18', '2004-06-12', '2005-12-30', '2004-06-02', '2004-06-02', '2004-06-02', '2004-08-14', '2004-05-24', '2004-09-08', '2004-05-25', '2004-09-02', '2004-06-02', '2004-06-02', '2004-06-24', '2004-11-08', '2005-12-16', '2004-06-02', '2004-11-01', '2004-05-24', '2005-12-16', '2005-05-05', '2004-09-09', '2004-09-09', '2005-06-20', '2005-05-24', '2004-05-24', '2004-08-16', '2004-09-09', '2004-11-01', '2005-06-20', '2005-02-06', '2005-02-06', '2005-05-24', '2004-10-26', '2004-09-09', '2005-05-24', '2004-06-02', '2004-07-28', '2005-12-16', '2004-06-24', '2005-04-21', '2005-07-07', '2004

In [21]:
# DONT execute if you already have the file
netflixUser =open("users.txt","w")
for k in filter.keys():
    netflixUser.write(k +",\n")
        

In [ ]:
# create columns for user-time matrix
# From https://stackoverflow.com/questions/7274267/print-all-day-dates-between-two-dates
start_date = date(1999, 11, 11) 
end_date = date(2005, 12, 31)    

delta = end_date - start_date   

days =[]
for i in range(delta.days + 1):
    day = start_date + timedelta(days=i)
    days.append(str(day))

In [23]:
print(days)

['1999-11-11', '1999-11-12', '1999-11-13', '1999-11-14', '1999-11-15', '1999-11-16', '1999-11-17', '1999-11-18', '1999-11-19', '1999-11-20', '1999-11-21', '1999-11-22', '1999-11-23', '1999-11-24', '1999-11-25', '1999-11-26', '1999-11-27', '1999-11-28', '1999-11-29', '1999-11-30', '1999-12-01', '1999-12-02', '1999-12-03', '1999-12-04', '1999-12-05', '1999-12-06', '1999-12-07', '1999-12-08', '1999-12-09', '1999-12-10', '1999-12-11', '1999-12-12', '1999-12-13', '1999-12-14', '1999-12-15', '1999-12-16', '1999-12-17', '1999-12-18', '1999-12-19', '1999-12-20', '1999-12-21', '1999-12-22', '1999-12-23', '1999-12-24', '1999-12-25', '1999-12-26', '1999-12-27', '1999-12-28', '1999-12-29', '1999-12-30', '1999-12-31', '2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08', '2000-01-09', '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13', '2000-01-14', '2000-01-15', '2000-01-16', '2000-01-17', '2000-01-18', '2000-01-19', '2000-01-20', '2000

In [ ]:
# load users, dont need this line if you have the users already defined elsewhere
netflixUserFile = open("users.txt","r")
netflixUser =[]
for line in netflixUserFile:
    res =line.replace(",\n","")
    netflixUser.append(res)
# From https://www.geeksforgeeks.org/different-ways-to-create-pandas-dataframe/
userTime = pd.DataFrame(0, index=netflixUser, columns=days)

In [26]:
display(userTime)


1999-11-11  1999-11-12  1999-11-13  1999-11-14  1999-11-15  \
1488844           0           0           0           0           0   
822109            0           0           0           0           0   
885013            0           0           0           0           0   
30878             0           0           0           0           0   
823519            0           0           0           0           0   
...             ...         ...         ...         ...         ...   
1410721           0           0           0           0           0   
1121358           0           0           0           0           0   
724334            0           0           0           0           0   
1613301           0           0           0           0           0   
2358447           0           0           0           0           0   

         1999-11-16  1999-11-17  1999-11-18  1999-11-19  1999-11-20  ...  \
1488844           0           0           0           0           0  ...   
822109            0           0           0           0           0  ...   
885013            0           0           0           0           0  ...   
30878             0           0           0           0           0  ...   
823519            0           0           0           0           0  ...   
...             ...         ...         ...         ...         ...  ...   
1410721           0           0           0           0           0  ...   
1121358           0           0           0           0           0  ...   
724334            0           0           0           0           0  ...   
1613301           0           0           0           0           0  ...   
2358447           0           0           0           0           0  ...   

         2005-12-22  2005-12-23  2005-12-24  2005-12-25  2005-12-26  \
1488844           0           0           0           0           0   
822109            0           0           0           0           0   
885013            0           0           0           0           0   
30878             0           0           0           0           0   
823519            0           0           0           0           0   
...             ...         ...         ...         ...         ...   
1410721           0           0           0           0           0   
1121358           0           0           0           0           0   
724334            0           0           0           0           0   
1613301           0           0           0           0           0   
2358447           0           0           0           0           0   

         2005-12-27  2005-12-28  2005-12-29  2005-12-30  2005-12-31  
1488844           0           0           0           0           0  
822109            0           0           0           0           0  
885013            0           0           0           0           0  
30878             0           0           0           0           0  
823519            0           0           0           0           0  
...             ...         ...         ...         ...         ...  
1410721           0           0           0           0           0  
1121358           0           0           0           0           0  
724334            0           0           0           0           0  
1613301           0           0           0           0           0  
2358447           0           0           0           0           0  

[236117 rows x 2243 columns]

In [28]:
# fill in the matrix cells
for user, times in user_time.items():
    for dates in times:
        userTime.at[user,dates] = 1

In [34]:
display(userTime)

1999-11-11  1999-11-12  1999-11-13  1999-11-14  1999-11-15  \
1488844           0           0           0           0           0   
822109            0           0           0           0           0   
885013            0           0           0           0           0   
30878             0           0           0           0           0   
823519            0           0           0           0           0   
...             ...         ...         ...         ...         ...   
1410721           0           0           0           0           0   
1121358           0           0           0           0           0   
724334            0           0           0           0           0   
1613301           0           0           0           0           0   
2358447           0           0           0           0           0   

         1999-11-16  1999-11-17  1999-11-18  1999-11-19  1999-11-20  ...  \
1488844           0           0           0           0           0  ...   
822109            0           0           0           0           0  ...   
885013            0           0           0           0           0  ...   
30878             0           0           0           0           0  ...   
823519            0           0           0           0           0  ...   
...             ...         ...         ...         ...         ...  ...   
1410721           0           0           0           0           0  ...   
1121358           0           0           0           0           0  ...   
724334            0           0           0           0           0  ...   
1613301           0           0           0           0           0  ...   
2358447           0           0           0           0           0  ...   

         2005-12-22  2005-12-23  2005-12-24  2005-12-25  2005-12-26  \
1488844           1           0           0           0           0   
822109            0           0           0           0           0   
885013            0           0           0           0           0   
30878             1           1           0           0           1   
823519            0           0           0           0           0   
...             ...         ...         ...         ...         ...   
1410721           0           0           0           0           0   
1121358           0           0           0           0           0   
724334            0           0           0           0           0   
1613301           0           0           0           0           0   
2358447           0           0           0           0           0   

         2005-12-27  2005-12-28  2005-12-29  2005-12-30  2005-12-31  
1488844           0           0           1           0           0  
822109            0           0           0           0           0  
885013            0           0           0           0           0  
30878             0           0           0           0           0  
823519            0           0           1           0           0  
...             ...         ...         ...         ...         ...  
1410721           0           0           0           0           0  
1121358           0           0           0           0           0  
724334            0           0           0           0           0  
1613301           0           0           0           0           0  
2358447           0           0           0           0           0  

[236117 rows x 2243 columns]

In [5]:
# save step for future code runs
userTime.to_csv('userTime.csv', index = True) 

NameError: name 'userTime' is not defined

In [35]:
items=[]
with open("data.txt") as file:
    for line in file:
        data = line.find(":")
        if data!=-1:
            item =line.replace(":\n","")
            items.append(int(item))
            

In [36]:
print(len(items))

17770


In [37]:
itemID =open("items.txt","w")
for i in items:
    itemID.write(str(i) +",\n")

In [ ]:
dataFile = open("data.txt","r")
outfile = open("dataTrimmed.txt", "a")

netflixUserFile = open("users.txt","r")
users ={}
count = 1
for line in netflixUserFile:
    res =line.replace(",\n","")
    users.update({res:count})
    count+=1

for line in dataFile:
    if ":" in line:
        outfile.write(line)
    else:
        row = line.split(",")
        user =row[0]
        if user in users:
            outfile.write(line)
# trimmed 11 million rows
# TODO: should trim further, by finding out which user is not active
# either by doing 365 days splice on matrix and seeing x amount of ratings by user
# or by doing a 365 days sliding window on user-time matrix

In [38]:
netflixUserFile = open("users.txt","r")
users ={}
pos = 0
for line in netflixUserFile:
    res =line.replace(",\n","")
    users.update({res:pos})
    pos+=1

# columns are ascending sequentially
dataFile = open("dataTrimmed.txt","r")
matrix=[]
for line in dataFile:
    if ":" in line:
        col = np.zeros(236117) # some bug in code where pos variable is changing so just hard coded it
        matrix.append(col)
    data = line.strip().split(',')
    if len(data) > 2:
        user =data[0]
        rating = int(data[1])
        pos = users[user]
        col[pos] = rating


In [45]:
matrix = np.array(matrix).T
print(matrix)

[[3. 0. 0. ... 3. 0. 4.]
 [5. 0. 0. ... 0. 0. 0.]
 [4. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Actually faster to not write it into a csv file and convert it into a dataframe. Keeping it as a numpy matrix seems to be the best option

In [126]:
userTime = pd.read_csv("userTime.csv") 

In [127]:
# userTime = userTime.drop(userTime.columns[0], axis=1)
display(userTime)


Unnamed: 0  1999-11-11  1999-11-12  1999-11-13  1999-11-14  \
0          1488844           0           0           0           0   
1           822109           0           0           0           0   
2           885013           0           0           0           0   
3            30878           0           0           0           0   
4           823519           0           0           0           0   
...            ...         ...         ...         ...         ...   
236112     1410721           0           0           0           0   
236113     1121358           0           0           0           0   
236114      724334           0           0           0           0   
236115     1613301           0           0           0           0   
236116     2358447           0           0           0           0   

        1999-11-15  1999-11-16  1999-11-17  1999-11-18  1999-11-19  ...  \
0                0           0           0           0           0  ...   
1                0           0           0           0           0  ...   
2                0           0           0           0           0  ...   
3                0           0           0           0           0  ...   
4                0           0           0           0           0  ...   
...            ...         ...         ...         ...         ...  ...   
236112           0           0           0           0           0  ...   
236113           0           0           0           0           0  ...   
236114           0           0           0           0           0  ...   
236115           0           0           0           0           0  ...   
236116           0           0           0           0           0  ...   

        2005-12-22  2005-12-23  2005-12-24  2005-12-25  2005-12-26  \
0                1           0           0           0           0   
1                0           0           0           0           0   
2                0           0           0           0           0   
3                1           1           0           0           1   
4                0           0           0           0           0   
...            ...         ...         ...         ...         ...   
236112           0           0           0           0           0   
236113           0           0           0           0           0   
236114           0           0           0           0           0   
236115           0           0           0           0           0   
236116           0           0           0           0           0   

        2005-12-27  2005-12-28  2005-12-29  2005-12-30  2005-12-31  
0                0           0           1           0           0  
1                0           0           0           0           0  
2                0           0           0           0           0  
3                0           0           0           0           0  
4                0           0           1           0           0  
...            ...         ...         ...         ...         ...  
236112           0           0           0           0           0  
236113           0           0           0           0           0  
236114           0           0           0           0           0  
236115           0           0           0           0           0  
236116           0           0           0           0           0  

[236117 rows x 2244 columns]

In [ ]:
def helper(matrix):
    toss = []
    for index, row in matrix.iterrows():
        res = np.sum(row[1:])
        if res<=15:
            # toss.append(int(row[0]))
            toss.append(index)
    return toss
            

In [168]:
# splice = userTime.iloc[:, 783:1148:1]
userID = userTime.loc[:,"Unnamed: 0"]
steps = 10
gran = 91
toss = set()

for i in range(0,13):
    start = i* gran + 783
    end = i*gran + 1148

    splice = userTime.iloc[:, start:end :1]
    res = helper(splice)
    for i in res:
        toss.add(i)
    print(start,end,len(userTime)-len(toss))

783 1148 15237
874 1239 14365
965 1330 13492
1056 1421 12819
1147 1512 12227
1238 1603 11773
1329 1694 11540
1420 1785 11300
1511 1876 11089
1602 1967 10838
1693 2058 10276
1784 2149 9719
1875 2240 8951
